language: python

os:
  - linux

python:
  - "3.5"
  - "3.7"

cache: pip

install:
  - pip install -r requirements.txt

script:
  - pylint -E --load-plugins pylint_django account config core match matchmaker player team
  - coverage run --source='.' manage.py test

after_success:
  - coveralls