# Generated by Django 2.0.8 on 2018-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50, verbose_name='Teamname')),
                ('players', models.ManyToManyField(to='player.Player')),
            ],
        ),
    ]
