# Generated by Django 2.0.8 on 2018-08-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_tscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tscore',
            field=models.PositiveIntegerField(default=1000, verbose_name='Team Score'),
        ),
    ]
