# Generated by Django 2.0.8 on 2018-08-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20180814_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tscore',
            field=models.PositiveIntegerField(default=0, verbose_name='Team Score'),
        ),
    ]
