# Generated by Django 2.0.8 on 2018-08-15 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20180814_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tscore',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Team Score'),
        ),
    ]
