# Generated by Django 2.0.8 on 2018-08-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20180815_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teamname'),
        ),
    ]
