# Generated by Django 2.1 on 2018-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_remove_team_tscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Teamname'),
        ),
    ]
