# Generated by Django 2.1.1 on 2018-09-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_team_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='user',
            new_name='owner',
        ),
    ]
