# Generated by Django 2.1.1 on 2018-09-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20180903_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
    ]
