# Generated by Django 2.0.8 on 2018-08-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pscore',
            field=models.PositiveIntegerField(default=1000, verbose_name='Player Score'),
        ),
    ]
