# Generated by Django 2.0.8 on 2018-08-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_pscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='pscore',
            new_name='rating',
        ),
    ]
