# Generated by Django 2.0.8 on 2018-08-14 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20180814_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.FloatField(default=1000, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Player Rating'),
        ),
    ]
