# Generated by Django 2.1 on 2018-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20180814_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nick',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nickname'),
        ),
    ]
