# Generated by Django 2.1.1 on 2018-09-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
    ]
