# Generated by Django 2.1.1 on 2018-09-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_player_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nick',
            field=models.CharField(max_length=50, verbose_name='Nickname'),
        ),
    ]
