# Generated by Django 2.0.8 on 2018-08-13 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Finish-Date')),
                ('firstteam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Team1', to='team.Team', verbose_name='Team 1')),
                ('secondteam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Team2', to='team.Team', verbose_name='Team 2')),
            ],
        ),
    ]
