# Generated by Django 2.0.8 on 2018-08-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='firstteam_goals',
            field=models.PositiveSmallIntegerField(default=1000, verbose_name='T1 goals'),
        ),
        migrations.AddField(
            model_name='match',
            name='secondteam_goals',
            field=models.PositiveSmallIntegerField(default=1000, verbose_name='T2 goals'),
        ),
    ]
