# Generated by Django 2.0.8 on 2018-08-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20180814_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='match',
            name='firstteam_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='T1 goals'),
        ),
        migrations.AlterField(
            model_name='match',
            name='secondteam_goals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='T2 goals'),
        ),
    ]
