# Generated by Django 2.1.1 on 2018-09-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_match_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='user',
        ),
    ]
